#ifndef KANGARO_HTTP_CODE_HEADER
#define KANGARO_HTTP_CODE_HEADER

#define KANGA_OK 0
#define KANGA_ERROR 1
#define KANGA_AGAIN 2

#define HTTP_VERSION "HTTP/1.1"
#define HTTP_SERVER "kangaro_1.0"

//Status Code
#define HTTP_STATUS_OK "200"
#define HTTP_STATUS_NOT_IMPLEMENT "501"
#define HTTP_STATUS_INTERNEL_ERROR "500"
#define HTTP_STATUS_BAD_REQUEST "400"
#define HTTP_STATUS_LENGTH_REQUIRED "411"
#define HTTP_STATUS_NOT_FOUND "404"

#endif
